## Programming Assignment 2

### Normalization Problem

In [97]:
import numpy as np

In [98]:
X=np.random.random((5,5))

In [99]:
mean=X.mean()

In [100]:
standard_deviation=X.std()

In [101]:
Z_array=(X-mean)/standard_deviation

In [102]:
np.save("X_normalized.npy", Z_array)

In [115]:
print(repr(X))

normalized=np.load("X_normalized.npy")
normalized

array([[0.14180879, 0.61070286, 0.3586823 , 0.86059853, 0.19274675],
       [0.20219922, 0.76311671, 0.3227388 , 0.63289916, 0.59434955],
       [0.55229215, 0.99596099, 0.55039339, 0.11109792, 0.12006031],
       [0.09093524, 0.10067076, 0.67310727, 0.86337194, 0.07252998],
       [0.39344623, 0.51611446, 0.12455799, 0.41292107, 0.21778868]])


array([[-1.00680811,  0.69627673, -0.21909502,  1.6039306 , -0.82179475],
       [-0.78746213,  1.24986383, -0.34964656,  0.77689661,  0.63687937],
       [ 0.48412136,  2.09558484,  0.47722482, -1.11835402, -1.08580142],
       [-1.1915875 , -1.15622683,  0.92293775,  1.61400398, -1.25843781],
       [-0.09282786,  0.35271924, -1.06946527, -0.0220927 , -0.73083916]])

### Divisible by 3 Problem

In [104]:
import numpy as np

In [105]:
squared_values = np.arange(1, 101) ** 2

In [106]:
squared_values

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [107]:
integer_arr = values.reshape(10, 10)

In [108]:
integer_arr

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [109]:
division=(integer_arr %3==0)

In [110]:
division

array([[False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False]])

In [111]:
divisible_by_3=array[division]

In [112]:
divisible_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [113]:
np.save("div_by_3.npy", divisible_by_3)

In [114]:
loaded=np.load("div_by_3.npy")
loaded

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])